<?php
$LAN = (object) array(
        'frontpagetitle' => 'JanhoSlide',
        'frontpagedefaultlink' => 'Normaali esitys',
        'frontpagecustomlink' => 'Muokattu esitys',
        'frontpagedatalink' => 'Hallitse dataa',
        'title' => 'JanhoSlide',
        'restitle' => 'Resoluutio',
        'reswidth' => 'Leveys',
        'resheight' => 'Korkeus',
        'reskeepratio' => 'Pakota kuvasuhde',
		'reschooseratio' => 'Kuvasuhde (leveys x korkeus)',
		'resusefullwindow' => 'Käytä ikkunan koko leveyttä ja korkeutta',
        'timetitle' => 'Vaihtumisajat',
        'timeswitchtime' => 'Vaihdon pituus',
        'timeswitchinfo' => 'Mainosten vahtumiseen menevä aika.',
        'timeshowtime' => 'Näyttöaika',
        'timeshowinfo' => 'Aika, jonka kuva näkyy ennen sen vaihtamista.',
        'switchtitle' => 'Vaihtumis tyylit',
        'readybutton' => 'Valmis',
        'datapagereturnheader' => 'Palaa alkuun',
        'datapagesendnewheader' => 'Lähetä uusi tiedosto:',
        'datapagesendnewfile' => 'Valitse tiedosto:',
        'datapagesendnewcheckbox' => 'Aseta päivä jolloin tämä tiedosto siirretään arkistoon',
        'datapagesendnewdate' => 'Viimeinen näyttöpäivä:',
        'datapageimagesheader' => 'Kuvat:',
        'datapagevideosheader' => 'Videot:',
        'datapageelementoptionsshowfull' => 'Avaa täysikokoisena',
        'datapageelementoptionsdelete' => 'Siirrä arkistoon');


